### ISSUE TITLE
Add an initial `app_for_spawners` fixture

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/pytest-jupyterhub#13]
### Proposed change

Let's add an initial `app_for_spawners` fixture (feel free to choose a better name for this as I don't usually do a great job naming things 😅).

This app would be a `pytest fixture` that would create a lightweight running JupyterHub  that will be used by in the test suites of different spawner implementations, starting from the `app` fixture in `jupyterhub`

### Steps

- [x] Using the info in https://docs.pytest.org/en/latest/how-to/writing_plugins.html and prior experience with the pytest plugin cookiecutter:
     - Identify a good place (file and directory) where this fixture should be added to
     - Figure out what's missing from this repository in order for it to be used as a pytest plugim 
        - Figuring out how to specify entrypoints through `pyproject.toml`
            - ~https://setuptools.pypa.io/en/latest/userguide/entry_point.html should help~
            - since we're using [hatch](https://hatch.pypa.io/latest) as the build system, these docs seem more appropriate -> https://hatch.pypa.io/latest/config/metadata/#plugins
            - https://docs.pytest.org/en/latest/how-to/writing_plugins.html#making-your-plugin-installable-by-others
 
- [ ] https://github.com/jupyterhub/pytest-jupyterhub/issues/25
    - [x] https://github.com/jupyterhub/pytest-jupyterhub/issues/20
- [x] #26
    - [ ] research ways to test the fixtures we just added to to make sure they are working as expected
    - [ ] write the tests
    - [ ] CI/CD
- [x] #27

### Notes
@Sheila-nk, a few notes:

- there is no timeline for finishing this and you should take all the time you need to do any research needed 📖 
- coming up with this initial fixture is a hard task, but will help us a lot in understanding the dynamics of the projects and will make subsequent similar tasks easier 🚀 
- feel free to open up separate issues for the sub-tasks. This can help with asking for help about a specific topic and organize the discussions based on the topics in each sub-task ✅ 
- please open PRs as early as possible, even if they are not perfect, so that you don't get stuck and get early feedback
- please feel to ask questions and clarifications whenever something is unclear either here on GitHub via issues or comments or privately when appropriate ❤️

**Comment by Sheila-nk** [comment]
@GeorgianaElena 😅 we are finally getting to the meat and potatoes of this project!
Thank you for creating this issue and providing a great blueprint on how to tackle this part of the project.

The name `app_for_spawners` works for now unless anyone has objections 😆 
I will for sure heed the advice you have provided in the notes section and ask questions as I go.

Thanks again ❤️
