### ISSUE TITLE
Rename the repository, package and module

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/pytest-jupyterhub#16]
### Context
The [`pytest` documentation](https://docs.pytest.org/en/latest/how-to/writing_plugins.html#writing-plugins) mentions a naming convention that the packages implementing `pytest` plugins should follow, that we missed when creating the repository first time:

_"All specifications and implementations follow the `pytest_` prefix naming convention, making them easy to distinguish and find."_

### Proposed change
I propose we change the repository name and the name of the package from `jupyterhub-pytest-plugin` to `pytest_jupyterhub` to respect the pytest convention and make the package more discoverable.

I believe all project that follow this convention will automatically go into the list at https://docs.pytest.org/en/latest/reference/plugin_list.html#plugin-list which will improve discoverability.

### Alternative options

We could also choose not to rename it, because I don't think not following the naming convention will create any issues in using the pytest plugins in this project. But since we are just begging the project and we don't have projects depending on it, nor a version released, we should take advantage of this and change it now.

### Who would use this feature?

Renaming it, will make the project more discoverable for projects or users wanting to test their own jupyterhub `spawner`
 and/or `authenticator` implementations using these plugins.

### (Optional): Suggest a solution

- [ ] @GeorgianaElena renames the repository to `pytest-jupyterhub`
- [ ] @GeorgianaElena recreates the RTD project per https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-my-project-slug-the-url-your-docs-are-served-at
- [ ] @Sheila-nk:
     - [ ] renames the package name from `jupyterhub-pytest-plugin` to `pytest-jupyterhub`
     - [ ] renames the module name from `jupyterhub-pytest-plugin` to `pytest_jupyterhub`
- [ ] ..?

**Comment by Sheila-nk** [comment]
From looking over the listed projects in the [pytest plugin-list](https://docs.pytest.org/en/latest/reference/plugin_list.html#plugin-list) the `pytest_` naming convention is specific to only the plugin repository and the plugin package. The module does not need to have the `pytest_` prefix.
So we can rename the repository to `pytest-jupyterhub` and the package to `pytest_jupyterhub` but maintain the name of the initial module `jupyterhub_spawners.py`.
What do you think?

**Comment by GeorgianaElena** [comment]
This sounds good! I'll proceed with renaming the repo then
