### ISSUE TITLE
Define a few spawner specific simple fixtures

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/pytest-jupyterhub#20]
### Proposed change

1. [x] Create a fixture that returns the spawer class to be used by the hub. Set it to return the base [`Spawner`](https://github.com/jupyterhub/jupyterhub/blob/36f74689c4dd7c9825da1fae9175469dde926cf9/jupyterhub/spawner.py#L74) class for this `jupyter_spawerner` pytest module.
    
2. [x] Create a fixture that's [requesting the fixture above ](https://docs.pytest.org/en/6.2.x/fixture.html#fixtures-can-request-other-fixtures) and returns a [traitlets.Config](https://traitlets.readthedocs.io/en/stable/config.html) object that [configures JupyterHub to use this spawner class](https://github.com/jupyterhub/yarnspawner/blob/1c40f529ddf9fd6217e9b8ae954fd669e4276c92/yarnspawner/tests/conftest.py#L23-L24).

3. [x] Create a fixture that returns an [traitlets.Config](https://traitlets.readthedocs.io/en/stable/config.html) object containing the spawner specific configuration options. Set it to return an empty config for this `jupyter_spawerner` pytest module.

#### Note
The [`app_for_spawners`](https://github.com/jupyterhub/pytest-jupyterhub/issues/13) future fixture will be requesting these fixtures and use them to configure the hub **before** starting the application. This will make hub initialization phase configurable by each spawner implementation.

**Comment by Sheila-nk** [comment]
@GeorgianaElena thank you for creating this issue 👏 
I will tackle them step by step as I do my research, and come back here if I have any questions or get stuck.

**Comment by GeorgianaElena** [comment]
> Or are you talking about other configuration options specific to different spawners, eg: YarnSpawner that uses the Kerberos protocol has attributes like principal and keytab

Yes, through "spawner specific configuration options",  I was referring to the config that sets spawner attributes rather than configuring the hub.

For example:

- This **configures the hub** to use the `DockerSpawner` spawner:
   ```python
   c.JupyterHub.spawner_class = DockerSpawner
   ```

- This **configures the spawner** DockerSpawner to use a specific image:
  ```python
  c.DockerSpawner.image = f"jupyterhub/singleuser:{tag}"
  ```

**Comment by GeorgianaElena** [comment]
This now complete 🎉 🎉
