### ISSUE TITLE
Add documentation about the `app_for_spawners` fixture

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/pytest-jupyterhub#27]

**Comment by Sheila-nk** [comment]
I suggest closing this issue as it was resolved by the merging of PR #32

**Comment by Sheila-nk** [comment]
> @Sheila-nk, I agree! Feel free to close any resolved issues! Thank you!

@GeorgianaElena I have closed some but I am unable to close issues you opened.

**Comment by GeorgianaElena** [comment]
@Sheila-nk, I just sent you an invite to be a maintainer of this project 🚀 Once you accept that, you should have all the permissions needed to close issues and merge PRs 🎉

**Comment by Sheila-nk** [comment]
> @Sheila-nk, I just sent you an invite to be a maintainer of this project 🚀 Once you accept that, you should have all the permissions needed to close issues and merge PRs 🎉

🙀 This is such a privilege and an honor @GeorgianaElena. Thank you so much! I am 1000% accepting it! 🥇

**Comment by Sheila-nk** [comment]
Closing this issue as resolved by the merging of PR #32
