### ISSUE TITLE
Initial release of `pytest-jupyterhub`

### ISSUE THREAD

**Issue by Sheila-nk** [jupyterhub/pytest-jupyterhub#45]
In preparation for the alpha release of [`pytest-jupyterhub`](https://github.com/jupyterhub/pytest-jupyterhub), this issue will help us keep track of things we need to do to prepare for the release. Feel free to let me know if I have missed any steps.

- [x] #37
- [ ] #38
- [x] #46
- [x] include GitHub workflow badges
- [x] #47

**Comment by Sheila-nk** [comment]
The [RELEASE.md](https://github.com/jupyterhub/jupyterhub-python-repo-template/blob/d4bc77bea8a6066182d23f7cd86ee44ed1297e8c/RELEASE.md#L4) file in the [jupyterhub-python-repo-template](https://github.com/jupyterhub/jupyterhub-python-repo-template) provides a great guide for making a release.

**Comment by Sheila-nk** [comment]
Quick question @GeorgianaElena and @minrk 
I am currently working on updating the changelog using [github-activity](https://github-activity.readthedocs.io/en/latest/). 
I have PRs open for [updating the README file](https://github.com/jupyterhub/pytest-jupyterhub/pull/39) and [contributing guidelines](https://github.com/jupyterhub/pytest-jupyterhub/pull/44) and also plan on making more PRs before the release. Should I wait until all PRs related to the release are merged before creating a PR for the changelog? Should it be the last thing I work on?

**Comment by minrk** [comment]
You can wait, or you can make further PRs to the changelog if an initial changelog has been merged already.

Often, we open a work-in-progress PR to the changelog, and update it in-place a few times as preparation for a release. For example, [this one](https://github.com/jupyterhub/jupyterhub/pull/4375).

**Comment by consideRatio** [comment]
Great work on this project @Sheila-nk!

I figure we can go directly to an initial release versioned 0.1.0 rather than an alpha release like 0.1.0a1. Then we can do `pip install pytest-jupyterhub` and it will work without `pip install --pre pytest-jupyterhub` which also would install pre-releases like an alpha / beta / release candidate.

Overall, we have used preview releases like `beta` for new major versions in jupyterhub/jupyterhub, jupyterhub/zero-to-jupyterhub-k8s, but not in other projects so far.

**Comment by consideRatio** [comment]
> [...] the main purpose of the alpha release is so people can try out and test the project for bugs before the official initial release, yes? What's the beta release for?

There is Alpha releases, Beta releases, and release candidates. To my knowledge, the difference is not described in definite terms, but I have an expectation on an alpha release to be less mature than a beta release, and a beta release to be less mature than a release candidate.

Check out the pre-releases of jupyterlab 4, they have worked a long time on jupyterlab 4 and provided alpha releases for a long time, but are now transitioning to beta releases: https://pypi.org/project/jupyterlab/#history. Maybe they will also provide a release candidate - I'm not sure.

I figure before a project has become a bit mature and become adopted by a group of users, its less relevant to provide alpha/beta/rc pre-releases. But when there is a group of users adopting something, a subset of the group may want to trial the latest bugfixes and features earlier than others - and by doing so accept a possible regression or similar. In the case for a new project like this, i figure its either something you trial at all or not anyhow.

**Comment by consideRatio** [comment]
A jupyterlab goes for alpha -> beta -> release candidates even between minor versions it seems! (3.6.0, 3 is major, 6 is minor, 0 is patch)

![image](https://user-images.githubusercontent.com/3837114/232128243-5ee5cbc5-f08c-4458-a520-0ee7991d589f.png)

**Comment by manics** [comment]
I also think it's fine to go straight to 0.1.0. Anything less than 1.0.0 is generally assumed to be in development, unless there's evidence to the contrary, e.g. packages which are used in production but no-ones ever gotten round to bumping it to 1.0.0.

**Comment by Sheila-nk** [comment]
Thanks, @consideRatio  for the in-depth explanation and resources to help me understand versioning. 
It does make sense to go straight to 0.1.0 and then move from there as the project grows and gets more users.

I am currently working to update the changelog. Once merged, I will go ahead with the release.
