### ISSUE TITLE
setup project's code coverage

### ISSUE THREAD

**Issue by Sheila-nk** [jupyterhub/pytest-jupyterhub#47]
- `codecov` needs to be enabled for this repository to help track code coverage

**Comment by Sheila-nk** [comment]
@consideRatio thanks again for your help setting up this project on PyPI 💯 
I am wondering if I have the necessary permissions to set up [codecov](https://docs.codecov.com/docs/quick-start)?

**Comment by consideRatio** [comment]
I've not really used codecov myself, but looked into this in https://github.com/jupyterhub/pytest-jupyterhub/issues/47. I think the github workflow running a test job, should run pytest with the `--cov` flag, and include a final step running the codecov/coverage@v3 action.

Currently, we have it like:

https://github.com/jupyterhub/pytest-jupyterhub/blob/16886113e7aa6c0d40973e1defeb6046dc3e95c3/.github/workflows/test.yml#L64-L76

**Comment by Sheila-nk** [comment]
Ahh! Nice, thank you for opening the issue up for discussion and highlighting the steps one should follow when setting up codecov. 
It has definitely cleared up the uncertainty around codecov, especially with regard to permissions. I will make the changes in the `test.yaml` file and proceed from there 🙏🏾
