### ISSUE TITLE
Some more fixtures

### ISSUE THREAD

**Issue by minrk** [jupyterhub/pytest-jupyterhub#65]
### Proposed change

Having used this for a bit now (it's great!) I have some suggestions for more fixtures to add. The [pytest-jupyter](https://pytest-jupyter.readthedocs.io) extension is a great model, which has fixtures for starting _and talking to_ a Jupyter server.

- [ ] #67
- [ ] #68
- [ ] #69
- [ ] #70

### Who would use this feature?

Spawners, authenticators

**Comment by Sheila-nk** [comment]
Thanks @minrk ❤️ 
I'd like to convert all the suggested fixtures into individual issues for easier tracking if that's okay.

**Comment by minrk** [comment]
Closing in favor of individual Issues
